In [226]:
#!pip install openpyxl
#!pip install awesome-slugify
#!pip install numpy
#!pip install xlsxwriter

In [227]:
import numpy as np

In [228]:
import pandas as pd

df = pd.read_excel('../data/2020-06-15_PACIENTI.xlsx')
df

,NR CRT,SCJUA / UPU / SAJ,SEX,VARSTA,DATA DEBUT SIMPTOME,SIMPTOME LA DEBUT,DATA INTERNARII,LOCUL INTERNARII,SIMPTOME,SEMNE SI DIAGNOSTIC DE INTERNARE,...,6 DATA RETESTARE,6 REZULTAT RETESTARE,TESTARE NR..6,7 DATA RETESTARE,7 REZULTAT RETESTARE,TESTARE NR..7,8 DATA RETESTARE,8 REZULTAT RETESTARE,DATA DECES,MEDIC FAMILIE
0,1.0,SCJUA,M,54,15.04.2020,"XEROSTOMIE, AMETELI",15.04.2020,BOLI INFECTIOASE,"TEMPERATURA 36,3","SUSPICIUNE INFECTIE SARS COV 2, DIABET ZAHARAT...",...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
1,2.0,UPU,M,73,2020-05-19 00:00:00,VERTIJ CEFALEE DURERE TORACICA,NaN,NaN,NaN,NaN,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
2,3.0,UPU,M,65,2020-05-14 00:00:00,VERTIJ TULBURARI DE ECHILIBRU,2020-05-14 00:00:00,BIALASER,VERTIJ VARSATURI,SUSPICIUNE INFECTIE SARS COV 2 SINDROM VEST...,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
3,4.0,UPU,F,76,2020-05-15 00:00:00,"VARSATURI, FEBRA",2020-05-15 00:00:00,BIALASER,"DURERE IN HIPOCONDRUL DREPT, VARSATURI",SUSPICIUNE INFECTIE SARS COV2; INSUFICIENTA VE...,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
4,5.0,UPU,F,16,2020-04-17 00:00:00,"varsaturi, scaune diareice, dureri abdominale",2020-04-21 00:00:00,Pediatrie 1,"faringe hiperemic, amigdale hipertrofice,epiga...",Gastroenterita acuta. Sdr. dureros abdominal.S...,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6494,5321.0,SAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
6495,5322.0,SAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
6496,5323.0,SAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
6497,5324.0,SAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN
6498,5325.0,SAJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN

# Initial observations
Having a first look at the raw data, we can observe that the content is dirty. As [Ben Perlmutter](https://chartio.com/blog/the-importance-of-good-data-hygiene-data-lakes-warehouses-and-hygiene/) says:

> "Good data hygiene is what you see in a well-organized data warehouse. All the tables and relationships are well-ordered and organized, with common patterns for names and datatypes that make sense in relation to each other."

In our case, we aim for:
- Well named columns
- Common data types for specific columns
- And more

## Step 1: Rename column names
Our aim is to have short, clear and readable column names in our dataframe. We agree on a naming convention with slugs. Usually, a slug helps us to identify a particular objects in an easy-to-read form.

In our case, we define new column names as slugs in order to follow the columns easier while reading or processing them. We use a Python flexible [slugify](https://pypi.org/project/awesome-slugify/) function.

For example:

```python
slugify('Any Text', to_lower=True, separator='_').upper()  # 'ANY_TEXT'

```

In [229]:
from slugify import slugify
renaming_map = {name: slugify(name, to_lower=True, separator='_').upper() for name in df.columns}
pd.DataFrame.from_dict(renaming_map, orient='index', columns=['new name'])

                                                                                  new name
NR CRT                                                                              NR_CRT
SCJUA / UPU / SAJ                                                            SCJUA_UPU_SAJ
SEX                                                                                    SEX
VARSTA                                                                              VARSTA
DATA DEBUT SIMPTOME                                                    DATA_DEBUT_SIMPTOME
SIMPTOME LA DEBUT                                                        SIMPTOME_LA_DEBUT
DATA INTERNARII                                                            DATA_INTERNARII
LOCUL INTERNARII                                                          LOCUL_INTERNARII
SIMPTOME                                                                          SIMPTOME
SEMNE SI DIAGNOSTIC DE INTERNARE                          SEMNE_SI_DIAGNOSTIC_DE_INTERNARE
ISTORICUL DE CALATORIE SI PERIOADA                      ISTORICUL_DE_CALATORIE_SI_PERIOADA
MOD CALATORIE AVION, MASINA, AUTOCAR ETC.           MOD_CALATORIE_AVION_MASINA_AUTOCAR_ETC
CONTACT CU UN CAZ CONFIRMAT                                    CONTACT_CU_UN_CAZ_CONFIRMAT
TESTARE NR.                                                                     TESTARE_NR
1                                     DATA TEST...                          1_DATA_TESTARE
1             REZULTAT TESTARE                                          1_REZULTAT_TESTARE
TESTARE NR..1                                                                 TESTARE_NR_1
2                                     DATA RETE...                        2_DATA_RETESTARE
2             REZULTAT RETESTARE                                      2_REZULTAT_RETESTARE
TESTARE NR..2                                                                 TESTARE_NR_2
3                                     DATA RETE...                        3_DATA_RETESTARE
3             REZULTAT RETESTARE                                      3_REZULTAT_RETESTARE
TESTARE NR..3                                                                 TESTARE_NR_3
4                                     DATA RETE...                        4_DATA_RETESTARE
4             REZULTAT RETESTARE                                      4_REZULTAT_RETESTARE
TESTARE NR..4                                                                 TESTARE_NR_4
5                                     DATA RETE...                        5_DATA_RETESTARE
5             REZULTAT RETESTARE                                      5_REZULTAT_RETESTARE
TESTARE NR..5                                                                 TESTARE_NR_5
6                                     DATA RETE...                        6_DATA_RETESTARE
6             REZULTAT RETESTARE                                      6_REZULTAT_RETESTARE
TESTARE NR..6                                                                 TESTARE_NR_6
7                                     DATA RETE...                        7_DATA_RETESTARE
7             REZULTAT RETESTARE                                      7_REZULTAT_RETESTARE
TESTARE NR..7                                                                 TESTARE_NR_7
8                                     DATA RETE...                        8_DATA_RETESTARE
8             REZULTAT RETESTARE                                      8_REZULTAT_RETESTARE
DATA DECES                                                                      DATA_DECES
MEDIC FAMILIE                                                                MEDIC_FAMILIE

In [230]:
df.rename(renaming_map, axis=1, inplace=True) # inplace=True will propagate the changes on our dataframe

In [231]:
df.fillna('', inplace=True)

In [232]:
df

,NR_CRT,SCJUA_UPU_SAJ,SEX,VARSTA,DATA_DEBUT_SIMPTOME,SIMPTOME_LA_DEBUT,DATA_INTERNARII,LOCUL_INTERNARII,SIMPTOME,SEMNE_SI_DIAGNOSTIC_DE_INTERNARE,...,6_DATA_RETESTARE,6_REZULTAT_RETESTARE,TESTARE_NR_6,7_DATA_RETESTARE,7_REZULTAT_RETESTARE,TESTARE_NR_7,8_DATA_RETESTARE,8_REZULTAT_RETESTARE,DATA_DECES,MEDIC_FAMILIE
0,1.0,SCJUA,M,54,15.04.2020,"XEROSTOMIE, AMETELI",15.04.2020,BOLI INFECTIOASE,"TEMPERATURA 36,3","SUSPICIUNE INFECTIE SARS COV 2, DIABET ZAHARAT...",...,NaT,,,NaT,,,NaT,,,
1,2.0,UPU,M,73,2020-05-19 00:00:00,VERTIJ CEFALEE DURERE TORACICA,,,,,...,NaT,,,NaT,,,NaT,,,
2,3.0,UPU,M,65,2020-05-14 00:00:00,VERTIJ TULBURARI DE ECHILIBRU,2020-05-14 00:00:00,BIALASER,VERTIJ VARSATURI,SUSPICIUNE INFECTIE SARS COV 2 SINDROM VEST...,...,NaT,,,NaT,,,NaT,,,
3,4.0,UPU,F,76,2020-05-15 00:00:00,"VARSATURI, FEBRA",2020-05-15 00:00:00,BIALASER,"DURERE IN HIPOCONDRUL DREPT, VARSATURI",SUSPICIUNE INFECTIE SARS COV2; INSUFICIENTA VE...,...,NaT,,,NaT,,,NaT,,,
4,5.0,UPU,F,16,2020-04-17 00:00:00,"varsaturi, scaune diareice, dureri abdominale",2020-04-21 00:00:00,Pediatrie 1,"faringe hiperemic, amigdale hipertrofice,epiga...",Gastroenterita acuta. Sdr. dureros abdominal.S...,...,NaT,,,NaT,,,NaT,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6494,5321.0,SAJ,,,,,,,,,...,NaT,,,NaT,,,NaT,,,
6495,5322.0,SAJ,,,,,,,,,...,NaT,,,NaT,,,NaT,,,
6496,5323.0,SAJ,,,,,,,,,...,NaT,,,NaT,,,NaT,,,
6497,5324.0,SAJ,,,,,,,,,...,NaT,,,NaT,,,NaT,,,
6498,5325.0,SAJ,,,,,,,,,...,NaT,,,NaT,,,NaT,,,

## Step 2: Have common data types for specific columns

### Everything is a string first
As we do not know our data yet, we convert all the information to string (uppercase) to get a more clean and readable format.

In [233]:
df = df.apply(lambda x: x.astype(str).str.upper())
df

,NR_CRT,SCJUA_UPU_SAJ,SEX,VARSTA,DATA_DEBUT_SIMPTOME,SIMPTOME_LA_DEBUT,DATA_INTERNARII,LOCUL_INTERNARII,SIMPTOME,SEMNE_SI_DIAGNOSTIC_DE_INTERNARE,...,6_DATA_RETESTARE,6_REZULTAT_RETESTARE,TESTARE_NR_6,7_DATA_RETESTARE,7_REZULTAT_RETESTARE,TESTARE_NR_7,8_DATA_RETESTARE,8_REZULTAT_RETESTARE,DATA_DECES,MEDIC_FAMILIE
0,1.0,SCJUA,M,54,15.04.2020,"XEROSTOMIE, AMETELI",15.04.2020,BOLI INFECTIOASE,"TEMPERATURA 36,3","SUSPICIUNE INFECTIE SARS COV 2, DIABET ZAHARAT...",...,NAT,,,NAT,,,NAT,,,
1,2.0,UPU,M,73,2020-05-19 00:00:00,VERTIJ CEFALEE DURERE TORACICA,,,,,...,NAT,,,NAT,,,NAT,,,
2,3.0,UPU,M,65,2020-05-14 00:00:00,VERTIJ TULBURARI DE ECHILIBRU,2020-05-14 00:00:00,BIALASER,VERTIJ VARSATURI,SUSPICIUNE INFECTIE SARS COV 2 SINDROM VEST...,...,NAT,,,NAT,,,NAT,,,
3,4.0,UPU,F,76,2020-05-15 00:00:00,"VARSATURI, FEBRA",2020-05-15 00:00:00,BIALASER,"DURERE IN HIPOCONDRUL DREPT, VARSATURI",SUSPICIUNE INFECTIE SARS COV2; INSUFICIENTA VE...,...,NAT,,,NAT,,,NAT,,,
4,5.0,UPU,F,16,2020-04-17 00:00:00,"VARSATURI, SCAUNE DIAREICE, DURERI ABDOMINALE",2020-04-21 00:00:00,PEDIATRIE 1,"FARINGE HIPEREMIC, AMIGDALE HIPERTROFICE,EPIGA...",GASTROENTERITA ACUTA. SDR. DUREROS ABDOMINAL.S...,...,NAT,,,NAT,,,NAT,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6494,5321.0,SAJ,,,,,,,,,...,NAT,,,NAT,,,NAT,,,
6495,5322.0,SAJ,,,,,,,,,...,NAT,,,NAT,,,NAT,,,
6496,5323.0,SAJ,,,,,,,,,...,NAT,,,NAT,,,NAT,,,
6497,5324.0,SAJ,,,,,,,,,...,NAT,,,NAT,,,NAT,,,
6498,5325.0,SAJ,,,,,,,,,...,NAT,,,NAT,,,NAT,,,

In [234]:
df['SEX'].value_counts()

F         3720
M         2719
            52
F            6
F            1
 M           1
Name: SEX, dtype: int64

In [235]:
df['DATA_DEBUT_SIMPTOME'].value_counts()

                       4489
2020-04-27 00:00:00      68
2020-04-15 00:00:00      67
2020-05-04 00:00:00      59
2020-04-10 00:00:00      57
                       ...
43937                     1
08.04 2020                1
11.04.020                 1
03.05.2020                1
20.05,2020                1
Name: DATA_DEBUT_SIMPTOME, Length: 173, dtype: int64

In [236]:
df['VARSTA'].value_counts()

                         261
52                       179
50                       159
45                       153
49                       142
                        ...
9 ANI                      1
7 ANI 1 LUNA               1
                   27      1
                   29      1
7 ZILE                     1
Name: VARSTA, Length: 129, dtype: int64

In [237]:
df['SEX'].value_counts()

F         3720
M         2719
            52
F            6
F            1
 M           1
Name: SEX, dtype: int64

## Strip the strings

In case of `SEX` columns, we observe that only converting to string and making uppercase is not enough to uniform the data. We have conceptually the same values that are counted together. As this might be the case for each column in part, we will `strip` (remove spaces at the beginning and at the end of the string) `all the values` in the dataset.

In [238]:
df = df.apply(lambda x: x.astype(str).str.strip())

In [239]:
df['SEX'].value_counts()

F    3727
M    2720
       52
Name: SEX, dtype: int64

In [240]:
df['SIMPTOME'].value_counts()

                                             5099
ASIMPTOMATIC                                  274
ASIMPTOMATICA                                 262
ASIMPTOMATIC COVID                             90
NU ARE                                         42
                                             ...
STARE GENERALA RELATIV BUNA,DURERE LOCALA       1
FRISON INAPETENTA                               1
FRISON, FEBRA 37,7                              1
GREATA INAPATENTA  CEFALEE                      1
CEFALEE,STARE GENERALA GRAVA                    1
Name: SIMPTOME, Length: 530, dtype: int64

In [241]:
df['SIMPTOME'].describe()

count     6499
unique     530
top
freq      5099
Name: SIMPTOME, dtype: object

### Convert date type
We can see that our dataset contains multiple columns with date type values which might be important for understanding how COVID spreads around population in time.

[Pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html) allows us to parse time series information from various sources and formats. By passing `errors='coerce'` parameter, we convert unparsable data to NaT (not a time):

```python
pd.to_datetime(["2009/07/31", "asd"], errors="coerce")
# DatetimeIndex(['2009-07-31', 'NaT'], dtype='datetime64[ns]', freq=None)
```

We manually decide which columns are concerned:
```python
['DATA_DEBUT_SIMPTOME',
 'DATA_INTERNARII',
 '1_DATA_TESTARE',
 '2_DATA_RETESTARE',
 '3_DATA_RETESTARE',
 '4_DATA_RETESTARE',
 '5_DATA_RETESTARE',
 '6_DATA_RETESTARE',
 '7_DATA_RETESTARE',
 '8_DATA_RETESTARE',
 'DATA_DECES']
```

Because the data was manually inserted, different date formats can be found in our dataset. When proccessing iregular format, we will see some warnings as follows:

In [242]:
pd.to_datetime(['15.04.2020', '17 05 2020', 'asd'], errors='coerce')

/tmp/ipykernel_54/578062254.py:1: UserWarning: Parsing '15.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  pd.to_datetime(['15.04.2020', '17 05 2020', 'asd'], errors='coerce')
/tmp/ipykernel_54/578062254.py:1: UserWarning: Parsing '17 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  pd.to_datetime(['15.04.2020', '17 05 2020', 'asd'], errors='coerce')

DatetimeIndex(['2020-04-15', '2020-05-17', 'NaT'], dtype='datetime64[ns]', freq=None)

But we can see that pandas knows how to infer the correct date for some cases.

In [243]:
DATETIME_COLUMN_NAMES = ["DATA_DEBUT_SIMPTOME", "DATA_INTERNARII", "1_DATA_TESTARE", "2_DATA_RETESTARE", "3_DATA_RETESTARE", "4_DATA_RETESTARE", "5_DATA_RETESTARE", "6_DATA_RETESTARE", "7_DATA_RETESTARE", "8_DATA_RETESTARE", "DATA_DECES"]

for column_name in DATETIME_COLUMN_NAMES:
    df[column_name] = pd.to_datetime(df[column_name], errors='coerce')

/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '15.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '14.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '18.05.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '21.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '25.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '17.05.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '13.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '18.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '28.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '27.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '23.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '20.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '30.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '13 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '16 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '21 04 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '25.04 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '14 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '15 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '17 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '16.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '15.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '28.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '18.05.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '21.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '17.05.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '14.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '13.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '27.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '19.02.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '17.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '20.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '25.04 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '30.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '13 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '16 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '21 04 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '17 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '29.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '15.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '14.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '13.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '21.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '19.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '17.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '25.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '28.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '27.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '16.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '18.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '20.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '30.04.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '21 04 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/opt/conda/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '15 05 2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)

In [244]:
df

,NR_CRT,SCJUA_UPU_SAJ,SEX,VARSTA,DATA_DEBUT_SIMPTOME,SIMPTOME_LA_DEBUT,DATA_INTERNARII,LOCUL_INTERNARII,SIMPTOME,SEMNE_SI_DIAGNOSTIC_DE_INTERNARE,...,6_DATA_RETESTARE,6_REZULTAT_RETESTARE,TESTARE_NR_6,7_DATA_RETESTARE,7_REZULTAT_RETESTARE,TESTARE_NR_7,8_DATA_RETESTARE,8_REZULTAT_RETESTARE,DATA_DECES,MEDIC_FAMILIE
0,1.0,SCJUA,M,54,2020-04-15,"XEROSTOMIE, AMETELI",2020-04-15,BOLI INFECTIOASE,"TEMPERATURA 36,3","SUSPICIUNE INFECTIE SARS COV 2, DIABET ZAHARAT...",...,NaT,,,NaT,,,NaT,,NaT,
1,2.0,UPU,M,73,2020-05-19,VERTIJ CEFALEE DURERE TORACICA,NaT,,,,...,NaT,,,NaT,,,NaT,,NaT,
2,3.0,UPU,M,65,2020-05-14,VERTIJ TULBURARI DE ECHILIBRU,2020-05-14,BIALASER,VERTIJ VARSATURI,SUSPICIUNE INFECTIE SARS COV 2 SINDROM VEST...,...,NaT,,,NaT,,,NaT,,NaT,
3,4.0,UPU,F,76,2020-05-15,"VARSATURI, FEBRA",2020-05-15,BIALASER,"DURERE IN HIPOCONDRUL DREPT, VARSATURI",SUSPICIUNE INFECTIE SARS COV2; INSUFICIENTA VE...,...,NaT,,,NaT,,,NaT,,NaT,
4,5.0,UPU,F,16,2020-04-17,"VARSATURI, SCAUNE DIAREICE, DURERI ABDOMINALE",2020-04-21,PEDIATRIE 1,"FARINGE HIPEREMIC, AMIGDALE HIPERTROFICE,EPIGA...",GASTROENTERITA ACUTA. SDR. DUREROS ABDOMINAL.S...,...,NaT,,,NaT,,,NaT,,NaT,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6494,5321.0,SAJ,,,NaT,,NaT,,,,...,NaT,,,NaT,,,NaT,,NaT,
6495,5322.0,SAJ,,,NaT,,NaT,,,,...,NaT,,,NaT,,,NaT,,NaT,
6496,5323.0,SAJ,,,NaT,,NaT,,,,...,NaT,,,NaT,,,NaT,,NaT,
6497,5324.0,SAJ,,,NaT,,NaT,,,,...,NaT,,,NaT,,,NaT,,NaT,
6498,5325.0,SAJ,,,NaT,,NaT,,,,...,NaT,,,NaT,,,NaT,,NaT,

In [245]:
df['1_REZULTAT_TESTARE'].value_counts()

NEGATIV         5228
POZITIV          622
                 538
NECONCLUDENT     110
NEGATIB            1
Name: 1_REZULTAT_TESTARE, dtype: int64

In [246]:
df['2_REZULTAT_RETESTARE'].value_counts()

                5176
NEGATIV         1102
POZITIV          201
NECONCLUDENT      19
NEGATOV            1
Name: 2_REZULTAT_RETESTARE, dtype: int64

In [247]:
df['3_REZULTAT_RETESTARE'].value_counts()

                5962
NEGATIV          445
POZITIV           78
NECONCLUDENT      14
Name: 3_REZULTAT_RETESTARE, dtype: int64

In [248]:
df['4_REZULTAT_RETESTARE'].value_counts()

                6304
NEGATIV          162
POZITIV           29
NECONCLUDENT       4
Name: 4_REZULTAT_RETESTARE, dtype: int64

In [249]:
df['5_REZULTAT_RETESTARE'].value_counts()

                6413
NEGATIV           76
POZITIV            9
NECONCLUDENT       1
Name: 5_REZULTAT_RETESTARE, dtype: int64

In [250]:
df['6_REZULTAT_RETESTARE'].value_counts()

           6468
NEGATIV      27
POZITIV       4
Name: 6_REZULTAT_RETESTARE, dtype: int64

In [251]:
df['7_REZULTAT_RETESTARE'].value_counts()

           6491
NEGATIV       7
POZITIV       1
Name: 7_REZULTAT_RETESTARE, dtype: int64

In [252]:
df['8_REZULTAT_RETESTARE'].value_counts()

           6497
POZITIV       2
Name: 8_REZULTAT_RETESTARE, dtype: int64

In [253]:
df['DATA_DECES'].value_counts()

Series([], Name: DATA_DECES, dtype: int64)

In [254]:
writer = pd.ExcelWriter('../data/2020-06-15_PACIENTI_FORMATTED.xlsx', engine='xlsxwriter')

In [255]:
df.to_excel(writer, sheet_name='formatted_data', na_rep='', index=False)

In [256]:
writer.save()